[tool]
id = "com.thelightphone.lightnycsubway"
label = "Subway Times"
versionCode = 2
versionName = "1.1.0"
permissions = ["android.permission.INTERNET"]
# Running on the LightOS emulator? swap the serverPackage below:
# serverPackage = "com.thelightphone.sdk.emulator"
serverPackage = "com.lightos"
